# Use postgres/example user/password credentials
#version: '3.9'

services:
  sprint:
    build: ./skatert
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn skatert.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./skatert:/skatert
    ports:
      - "8000:8000"
    depends_on:
      - db2
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db2:5433/postgres
    networks:
      - mynetwork

  db2:
    container_name: db2
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - db2:/var/lib/postgresql/data
    ports:
        - "5433:5432"
    networks:
      - mynetwork

volumes:
    db2:
      driver: local

networks:
  mynetwork:
    external: true