services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn skatert.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
