# Generated by Django 5.1.5 on 2025-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_description_detail_category_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecloth',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Клеенки'),
        ),
    ]
