# Generated by Django 5.1.4 on 2025-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tablecloth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablecloth',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='tablecloth',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='oilcloth_images/'),
        ),
        migrations.AddField(
            model_name='tablecloth',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='oilcloth_images/'),
        ),
    ]
